name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 推送到 main 分支触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 拉取仓库源码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ 设置 Go 环境（可选，如果 Dockerfile 已经处理可以省略）
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.24.5"

    # 3️⃣ 登录 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4️⃣ Build Docker 镜像
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hulio-user:latest .

    # 5️⃣ Push 镜像到 Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hulio-user:latest
